### ISSUE TITLE
Update full package repository structure

### ISSUE THREAD

**Issue by hhhapz** [discord-gophers/goapi-gen#20]
The current repository has a lot of redundant directories and has no Go code in the project root. This can most likely be updated to be more easy to work with, as well as easier to `go install`.

**Comment by Karitham** [comment]
Should we move /pkg/* to top level ?

We might as well move templates to top level too, and make them customizable.

`xo` has taken this a step further, and enables users to **dump** their templates, such that they can update/configure them by hand themselves, and then use them directly with the tool.

This refactor would also make it far easier to decouple the runtime package, and we might as well do #68 in the same way.
