### ISSUE TITLE
Proposal: Allow non-pointer optional fields

### ISSUE THREAD

**Issue by diamondburned** [discord-gophers/goapi-gen#76]
I propose a new `x-go-valuetype: true` attribute that, if true, will make the generator output a primitive type with an `,omitempty` attribute and without a pointer.

This particular use case is useful in a lot of cases where an omitted field and an empty value are treated the same:

```jsonc
{
  "id": "",  // useless
  "bio": "", // consider as empty in either cases
}
```

Either of these fields being `*string` isn't any more useful.

**Comment by Karitham** [comment]
Fixed by #82
